### ISSUE TITLE
Deploy to Azure not working

### ISSUE THREAD

**Issue by mattwoberts** [MicrosoftDX/Vorlonjs#295] opened 2016-01-19 15:44 UTC
Just went through the steps to deploy to azure. On completion, I navigate to the app and just see `You do not have permission to view this directory or page.`.

The deployment of the code seems to have happened OK. I've re-deployed the latest code, and still no joy. If it's relevant, I pushed to a North Europe region.

**Comment by meulta** [comment] 2016-01-19 16:53
Yep, sorry about that we are working on it :)

**Comment by mattwoberts** [comment] 2016-01-20 09:20
Cool.

Also (sorry to be such a downer!), it doesn't deploy to azure either if you follow the instructions here: https://channel9.msdn.com/Blogs/joeraio/Deploying-VorlonJS-to-Azure-Web-App-for-Remote-Debugging

I followed those instructions, but changed the package.json so that the version was 0.1.0, and on deployment, get loads of errors (pasted below). When it's finished nothing works.

Here's the log:


```
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)': function template has already been defined [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote:   D:\home\site\wwwroot\node_modules\nan\nan.h(256): note: see declaration of '_NanEnsureLocal'
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(661): error C2039: 'FreeCallback': is not a member of 'node' [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote:   D:\local\UserProfile\.node-gyp\4.2.3\include\node\node_object_wrap.h(8): note: see declaration of 'node'
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(661): error C2061: syntax error: identifier 'FreeCallback' [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(665): error C2065: 'callback': undeclared identifier [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(665): error C2065: 'hint': undeclared identifier [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New': none of the 4 overloads could convert all the argument types [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote:   D:\local\UserProfile\.node-gyp\4.2.3\include\node\node_buffer.h(43): note: could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
remote:   D:\local\UserProfile\.node-gyp\4.2.3\include\node\node_buffer.h(31): note: or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
remote:   D:\home\site\wwwroot\node_modules\nan\nan.h(672): note: while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(676): error C2440: 'return': cannot convert from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>' [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote:   D:\home\site\wwwroot\node_modules\nan\nan.h(676): note: No constructor could take the source type, or constructor overload resolution was ambiguous
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(683): error C2039: 'Use': is not a member of 'node::Buffer' [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote:   D:\local\UserProfile\.node-gyp\4.2.3\include\node\node_buffer.h(8): note: see declaration of 'node::Buffer'
remote: D:\home\site\wwwroot\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found [D:\home\site\wwwroot\node_modules\bufferutil\build\bufferutil.vcxproj]
remote: gyp ERR! build error 
remote: gyp ERR! stack Error: `msbuild` failed with exit code: 1
```

**Comment by liquidboy** [comment] 2016-01-27 05:38
any movement on this ? I really want to put vorlon on our web app and host the server in azure :)

**Comment by jcorioland** [comment] 2016-01-27 07:31
@liquidboy, @mattwoberts: we have an issue with the web app configuration... working on it... :)
There are two workarounds to make the Vorlon.JS working while this issue is not solved: 
- use the free website mode (limited socket number) 
- when other pricing, wait for the deployment to complete and restart the Azure Web App once you get the 403 error. 

It should work.

HTH
Julien

**Comment by cubitouch** [comment] 2016-01-27 11:18
When you say "free website mode" you mean "Free SKU"?
The deployment never seems to complete for me, I always get this:
![image](https://cloud.githubusercontent.com/assets/7486151/12611963/03be2f9a-c4f0-11e5-9057-bce9aeb126a7.png)

PS: restart doen't solve the App Service running issue).

**Comment by jcorioland** [comment] 2016-01-27 17:14
@cubitouch yep, free SKU. Are you trying to deploy master or dev ? thanks !

**Comment by liquidboy** [comment] 2016-01-27 21:53
I was UNABLE to deploy ANY of the branchs (master/dev/test deploy) to an "Australia EAST/South EAST" datacenter ....  

I was ABLE to deploy the "Master" branch to the "East US" datacenter

Seems like only certain datacenters work !!!

**Comment by cubitouch** [comment] 2016-01-28 08:40
@jcorioland I was on master branch. Dev branch deployment seems working for me on West Europe :)

**Comment by meulta** [comment] 2016-01-28 10:49
@liquidboy the issue is under investigation with azure team :) stay tuned !

**Comment by jcorioland** [comment] 2016-02-26 16:22
@mattwoberts, @cubitouch, @liquidboy can you retry to deploy (either from master or dev branch) and tell me if it's working now ? After few tests, I was not able to reproduce the error! Thanks :-)

**Comment by meulta** [comment] 2016-02-29 21:39
Issue fixed on our side.
Please reopen if needed :)

**Closed by meulta** 2016-02-29 21:39 UTC
Labels: bug

**Comment by CharlBest** [comment] 2016-04-22 09:42
Good day. I have this issue. Deployed my web api app from Visual Studio and then set up an deployment plan to watch my maser branch on github. When I deployed from vs I got the pretty blue azure screen saying you app is up and running but when I set up github deployment it pulled and deployed and then I got a blank html page saying "You do not have permission to view this directory or page." please help. thanks

**Comment by meulta** [comment] 2016-04-26 13:14
Hello @CharlBest 
Do you get any issue related to Vorlon.js ?

**Comment by valeriob** [comment] 2016-06-01 03:45
I'm not able do deploy master or dev, in any EU or US datacenter via https://deploy.azure.com

**Comment by mistrsoft** [comment] 2016-06-02 00:57
The same with me. Can't deploy to Australia SouthEast.
When I review the website in azure portal it fails on the step "Running deployment command..."
here's the log output

> Command: deploy.cmd
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Deleting file: 'hostingstart.html'
Copying file: '.dockerignore'
Copying file: '.gitattributes'
Copying file: '.gitignore'
Copying file: '.npmignore'
Copying file: 'azuredeploy-parameters.json'
Copying file: 'azuredeploy.json'
Copying file: 'build-docker-image.sh'
Copying file: 'CONTRIBUTING.md'
Copying file: 'disclaimer.js'
Copying file: 'Dockerfile'
Copying file: 'gulpfile.js'
Copying file: 'LICENSE'
Copying file: 'package.json'
Copying file: 'README.md'
Copying file: 'whatsnew.md'
Copying file: '.vscode\launch.json'
Copying file: '.vscode\settings.json'
Copying file: '.vscode\tasks.json'
Copying file: 'bin\vorlon'
Copying file: 'client samples\nodejs\app.js'
Copying file: 'client samples\nodejs\package.json'
Copying file: 'client samples\nodejs\.vscode\launch.json'
Copying file: 'client samples\webpage\.gitignore'
Copying file: 'client samples\webpage\bestpractices.css'
Copying file: 'client samples\webpage\bestpractices.html'
Copying file: 'client samples\webpage\browsersync.js'
Copying file: 'client samples\webpage\how-to-use-vorlon-in-production.html'
Copying file: 'client samples\webpage\index.css'
Copying file: 'client samples\webpage\index.html'
Copying file: 'client samples\webpage\package.json'
Copying file: 'client samples\webpage\readme.md'
Copying file: 'client samples\webpage\ship.svg'
Copying file: 'client samples\webpage\unitTestRunner.html'
Copying file: 'DeploymentTools\deployment-template.json'
Copying file: 'DeploymentTools\dev-deployment-template-parameters.json'
Copying file: 'DeploymentTools\post-deployment-template.json'
Copying file: 'DeploymentTools\preprod-deployment-template-parameters.json'
Copying file: 'DeploymentTools\production-deployment-template-parameters.json'
Copying file: 'DeploymentTools\production-deployment-template.json'
Copying file: 'DeploymentTools\production-post-deployment-template.json'
Copying file: 'DeploymentTools\production-preview-slot-deletion.ps1'
Copying file: 'desktop\.editorconfig'
Copying file: 'desktop\.gitattributes'
Copying file: 'desktop\.gitignore'
Copying file: 'desktop\gulpfile.js'
Copying file: 'desktop\main.css'
Copying file: 'desktop\package.json'
Copying file: 'desktop\README.md'
Omitting next output lines...
Start script "./Server/server.js" from package.json is not found.
Missing server.js/app.js files, web.config is not generated
Looking for app.js/server.js under site root.
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 4.2.3.
Selected npm version 3.5.1
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! fetch failed https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/dashdash/-/dashdash-1.13.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/dashdash/-/dashdash-1.13.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd
One or more errors occurred.
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd

**Comment by RSI-sanjayyadav** [comment] 2018-08-16 07:06
The current api-version doesn't support RBAC users. Please use a newer version instead.
