### ISSUE TITLE
Error require QUnit when accessing program

### ISSUE THREAD

**Issue by tbalouet** [MicrosoftDX/Vorlonjs#267] opened 2015-11-12 17:34 UTC
I tried using Vorlon, it was working great a long time ago, this time I reinstalled it, same configuration than before, but I get the following error when launching my program
![image](https://cloud.githubusercontent.com/assets/5400381/11125744/dd10b242-896b-11e5-9758-6c407ce63ef7.png)

Any idea? I don't require this file from my side, so it may be an installation problem, even though I didn't get any error while installing via npm

**Comment by meulta** [comment] 2015-11-12 17:35
Hello,

How are you referencing vorlon.js ? I see a mention of requirejs.

Thanks

**Comment by tbalouet** [comment] 2015-11-12 17:41
classic way : 
```
<script src="http://192.168.1.79:1337/vorlon.js"></script>
```
in the head

**Comment by meulta** [comment] 2015-11-12 17:58
Okay
Why is the screenshot displaying require.js ? is it one of your files you named like this?

**Comment by tbalouet** [comment] 2015-11-12 18:06
we are using require.js which is a file loading module, but we don't use it to load QUnit. Or maybe there's a redefinition of require on your side?

**Comment by meulta** [comment] 2015-11-12 19:18
Nop, we are not using requirejs.
Which is weird is that the error says it is happening in the require.js file... Could you hand me a full simple repro case ? With files i so i can test on my side?
Thanks

**Comment by tbalouet** [comment] 2015-11-16 09:21
Sadly it's quite a big project. I wanted to know if it was a known issue, I'll try to look it up by myself some more

**Comment by meulta** [comment] 2015-11-16 10:33
Can you try to add the reference to the vorlon.js script before everything else?

**Comment by meulta** [comment] 2015-11-21 16:25
Can you get the latest version from dev and try again ? 
I just wrote a fix for QUnit and I think this will help.

Thanks

**Comment by meulta** [comment] 2015-11-23 21:55
Closing this one, open it again if the issue is still here :)

**Closed by meulta** 2015-11-23 21:55 UTC
Labels: Investigating

**Comment by royto** [comment] 2015-11-25 08:45
I had the same issue with the 0.1.0. 
Switching to dev, it works well now. 
thanks

**Comment by tbalouet** [comment] 2015-11-25 16:05
Silly question (and sorry for the long delay), How do I get the dev version from npm?
Thanks!

**Comment by meulta** [comment] 2015-11-25 17:36
unfortunately, you cannot.

you need to 

`git clone http://github.com/microsoftdx/vorlonjs`
`git checkout dev `
`npm install`
`npm start`

**Comment by tbalouet** [comment] 2015-11-26 16:44
Yep, solved the problem, thanks!
