### ISSUE TITLE
console.log.apply  will TypeError: Object.getPrototypeOf called on non-object

### ISSUE THREAD

**Issue by raiscui** [MicrosoftDX/Vorlonjs#154] opened 2015-07-01 01:06 UTC
when i use self log function like this:
`var logs = function() {
      console.log.apply(console,args);
    };`

vorlon will throw error:
`TypeError: Object.getPrototypeOf called on non-object
    at Function.getPrototypeOf (native)
    at InteractiveConsoleClient.inspect (http://debug.tweens.io:9988/vorlon.js/default:46:32)
    at InteractiveConsoleClient.getMessages (http://debug.tweens.io:9988/vorlon.js/default:120:47)
    at http://debug.tweens.io:9988/vorlon.js/default:182:37
    at Console.e.Hook.e.(anonymous function) [as log] (http://debug.tweens.io:9988/vorlon.js/default:4:569)
    at angular.module.controller.logs (http://localhost:8100/js/app.js:21105:20)
    at m.angular.module.controller.$scope.UserDevicesUpdate (http://localhost:8100/js/app.js:21220:8)
    at http://localhost:8100/js/app.js:21214:15
    at m.$get.m.$emit (http://localhost:8100/libs/angular/angular.min.js:135:505)
    at Object.angular.module.factory.publish (http://localhost:8100/js/app.js:19280:19)e.Hook.e.(anonymous function) @ VM1470 default:4(anonymous function) @ angular.js:12285$get @ angular.js:8983$get.m.$emit @ angular.js:16016angular.module.factory.publish @ VM1480 app.js:19280(anonymous function) @ VM1480 app.js:20019(anonymous function) @ angular.js:17611e @ angular.js:5334(anonymous function) @ angular.js:5637`

**Comment by colbin8r** [comment] 2015-07-01 20:10
Hi @raiscui, thanks for reporting this. What is the value of the `args` variable in your `logs` function? Often a `Object.getPrototypeOf` call will fail when called on a null value.

**Comment by raiscui** [comment] 2015-07-02 03:22
o , sorry~
args is
`var args = Array.prototype.slice.call(arguments);`

and `console.log.apply(console,arguments)` has same things happening

**Comment by meulta** [comment] 2015-07-20 07:52
Hey @raiscui 

Sorry for the delay, we are on a vacation here :)

I am not able to reproduce your issue. Can you give me a full sample ?
Where and when does your code run when generating this error?

Thanks

**Comment by meulta** [comment] 2015-07-26 21:11
@raiscui can you provide us more info ? :)
Thanks

**Comment by meulta** [comment] 2015-07-28 20:48
@raiscui I close this issue as I have no news from you and are not able to reproduce.
Feel free to open again if you can send us more info ! :)

Thanks

**Closed by meulta** 2015-07-28 20:48 UTC
Labels: bug, More info required
