### ISSUE TITLE
Vorlon.js: waiting for socket.io to load...

### ISSUE THREAD

**Issue by marcesso** [MicrosoftDX/Vorlonjs#263] opened 2015-11-09 13:21 UTC
Hello,

After seeing the nice demo last Friday in Nantes, I would like to debug an angular website with vorlonjs.
I could deploy the dashboard successfully but I can't use it because the client is not reached.

Client-side, this is the main.scala.html template loaded:
```javascript
<!DOCTYPE html>
<html lang="en">
  <head>
    @styles
    <!-- Javascript files -->
    <script type='text/javascript' src='@routes.Assets.at("...")'></script>
    <script src='@routes.Assets.versioned("lib/requirejs/require.js")' data-main="/js/main" type="text/javascript"></script>
    <script src="http://127.0.0.1:1337/vorlon.max.js"></script>
    @scripts
  </head>
  <body>
    @container
  </body>
</html>
```
The client console shows this error:
```
"Vorlon.js: waiting for socket.io to load..." vorlon.max.js:1488:25
"Vorlon.js: please load socket.io before referencing vorlon.js or use includeSocketIO = true in your catalog.json file." vorlon.max.js:1493:21
```
I changed _socketIOWaitCount max from 10 to 50 and timeout from 1000 to 5000 to make sure waiting was enough => errors are still here.
So I loaded vorlonjs script before requirejs like that:
```javascript
   <script src="http://127.0.0.1:1337/vorlon.max.js"></script>
   <script src='@routes.Assets.versioned("lib/requirejs/require.js")' data-main="/js/main" type="text/javascript"></script>
```
The client is identified by the dashbord but my app is not fully loaded. Now the console error is:
```
Error: Mismatched anonymous define() module: function () {
		return QUnit;
	}
http://requirejs.org/docs/errors.html#mismatch    vorlon.max.js:2046:28
```
I can see this error in dashboard thus connexion is now established.

Should vorlonjs script be loaded before requirejs? Is there something missing? Can we use vorlon with angular and requirejs?

Thanks for your help,
Marie

**Comment by meulta** [comment] 2015-11-09 14:57
Hello !

Are you using Socket.io in your own app ?

**Comment by marcesso** [comment] 2015-11-09 15:11
No, I don't

**Comment by meulta** [comment] 2015-11-12 08:12
I'm on it :)

**Comment by marcesso** [comment] 2015-11-12 08:18
Thanks, let me know if you need further dependencies info about my angular website

**Comment by meulta** [comment] 2015-11-12 19:22
Ok i am pretty sure you have the same issue than #267 this seems to be related to using require.js.

Im still investigating :-)

**Comment by meulta** [comment] 2015-11-21 16:26
Can you get the latest version from dev and try again ? 
I just wrote a fix for QUnit and I think this will help.

Thanks

**Comment by meulta** [comment] 2015-11-23 21:55
Closing this one, open it again if the issue is still here :)

**Closed by meulta** 2015-11-23 21:55 UTC
Labels: Investigating

**Comment by marcesso** [comment] 2015-11-24 09:47
Sorry for the late response
I could try again and it works with dev version
I can't see anything in nginspector tab. However, I am not sure I did everything expected about vorlon compilation. So I will try again with master version when PR will be done and let you know.

Many thanks

**Comment by meulta** [comment] 2015-11-24 15:15
okay, if the nginspector does not work as expected do not hesitate to create an issue about it ! :)

**Comment by warpdesign** [comment] 2015-12-13 18:14
@meulta I'm getting the same error when trying to use vorlon.js (a big red banner appears at the top of my page with "Vorlon.js: please load socket.io before referencing vorlon.js or use includeSocketIO = true in your catalog.json file.").

Where is this catalog.json file ?

I'm not using socket.io in my app.

**Comment by meulta** [comment] 2015-12-14 08:28
It is in the node_modules/vorlon/server folder :)

**Comment by burakhanalkan** [comment] 2016-02-16 09:43
In the latest version of vorlon.js,  catalog.json does not exist in the server folder, instead config.json is available. Although I've added "includeSocketIO": true configuration in config.json, still I got the error "Vorlon.js: please load socket.io before referencing vorlon.js or use includeSocketIO = true in your catalog.json file"

**Comment by meulta** [comment] 2016-02-16 09:51
Can you share a bit more about what you are doing in the website you try to debug ?
Maybe share your code if you can.

Thanks :)

**Comment by burakhanalkan** [comment] 2016-02-16 09:58
As mentioned in documentation, I added <script src="http://localhost:1337/vorlon.js"></script> tag in my application, in index.html. I can reach vorlon.js dashboard when I browse http://localhost:1337 . However, while my app starts to running "Vorlon.js: please load socket.io before referencing vorlon.js or use includeSocketIO = true in your catalog.json file" error appears on browser console and big red banner appears instead of my app start page. I'm not using socket.io in my app, however I try to add includeSocketIO = true parameter but there is still the same error on browser console.

**Comment by meulta** [comment] 2016-02-16 10:13
Okay.
What other tech or framework do you use in your web app?
Did/can you try with a simple sample ? An empty page with just vorlon.js referenced?
Thanks

**Comment by burakhanalkan** [comment] 2016-02-16 11:36
OK, problem solved when I moved the vorlon js script tag as first script tag. Just simple as :)

**Comment by meulta** [comment] 2016-02-16 16:31
Perfect ! Thanks for keeping me up todate :)

**Comment by mildfuzz** [comment] 2016-05-06 09:10
I have the same issue. 

Using require for the app. I have no access to the page DOM until the script loads (third party dependancy)

I have no switched to manually writing a script tag and appended to head, but no darts. Get the same red banner. I have added the ```"includeSocketIO": true``` to Server/config.json and I have even tried loading socket.io from a CDN and waiting for it to load before loading vorlon, no darts :(

**Comment by mildfuzz** [comment] 2016-05-06 09:18
So I've just tried the dev branch, same issue.
